common:
  max_seq_len: 50

model:
  backbone:
    name: PPLCNet
    in_channel: 3
    scale: 1.0
  neck:
    name: CSPPAN
    list_in_c: [64, 128, 256, 512]
    out_c: 256
    kernel_size: 5
    num_csp_blocks: 1
    use_depthwise: true
    act: 'hard_swish'
  head:
    name: VastHead
    d_model: 256
    fea_size: [38, 38]  # 608/16
    vocab_size: 30
    n_bins: 608
    html_decoder:
      d_model: ${model.head.d_model}
      max_seq_len: ${common.max_seq_len}
      num_classes: ${model.head.vocab_size}
      n_layers: 3
      n_heads: 8
      ffn_hidden_dim: 512
      dropout: 0.1
    coord_decoder:
      d_model: ${model.head.d_model}
      max_seq_len: 4   # xmin, ymin, xmax, ymax
      num_classes: ${model.head.n_bins}
      n_layers: ${model.head.html_decoder.n_layers}
      n_heads: ${model.head.html_decoder.n_heads}
      ffn_hidden_dim: ${model.head.html_decoder.ffn_hidden_dim}
      dropout: ${model.head.html_decoder.dropout}
  pretrained: null

data:
  dataset:
    train:
      name: PubTabDataset
      data_dir: data/test_data
      anno_path: data/test_data/anno_train.jsonl

    val:
      name: PubTabDataset
      data_dir: data/test_data
      anno_path: data/test_data/anno_train.jsonl

    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: false
      - TableLabelEncode:  # get absolute box 
          max_text_length: ${common.max_seq_len}
          character_dict_path: data/table_structure_dict.txt
          learn_empty_box: false
          merge_no_span_structure: true
          replace_empty_cell_token: false
          loc_reg_num: 4 
      - TableBoxEncode:   # convert box format and normalize box coord in range(0, 1)
          in_box_format: xyxy
          out_box_format: xyxy
      - ResizeTableImage:  # resize preserve aspect ratio, no padding
          max_len: 608
          resize_bboxes: false  # because bb is normalized, no need to resize
      - NormalizeImage:
          scale: 1./255.
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          order: 'hwc'
      - PaddingTableImage:  # pad image at the right and bottom to make it square. After this padding, the normalized box coord is no longer true
          size: [608, 608]
      - ToCHWImage:
      - KeepKeys:
          keep_keys: ['image', 'structure', 'padding_mask', 'bboxes', 'abs_bboxes', 'bbox_masks', 'shape']

    augmentations: []

  loader:
    shuffle: False
    drop_last: False
    batch_size: 1
    num_workers: 0

optimizer:
  name: AdamW
  lr: 0.001
  weight_decay: 0.0
  betas: [0.9, 0.999]


scheduler:
  name: CosineAnnealingLR
  T_max: ${trainer.max_epochs}
  eta_min: 1e-6

loss:
  name: VastLoss
  html_weight: 1.0
  coord_weight: 1.0
  visual_align_weight: 1.0
  infoNCE_loss:
    temperature: 0.04

trainer:
  ckpt_dir: ckpt/vast/exp0_1_image
  max_epochs: 300
  min_epochs: 30
  device: cpu
  log_interval: 1  # step
